SenzaComponents:
- Configuration:
    Type: Senza::StupsAutoConfiguration
- AppServer:
    IamRoles:
    - Ref: EtcdRole
    InstanceType: t2.nano
    SecurityGroups:
    - Fn::GetAtt:
      - EtcdSecurityGroup
      - GroupId
    TaupageConfig:
      ports:
        2379: 2379
        2380: 2380
      runtime: Docker
      # https://github.com/zalando/stups-etcd-cluster#step-1-create-an-etcd-cluster
      source: 'registry.opensource.zalan.do/acid/etcd-cluster:2.2.2-p7'
      environment:
        HOSTED_ZONE: 'myteam.example.org'
      application_logrotate_size: 50M
      application_logrotate_interval: weekly
      application_logrotate_rotate: 4
      mounts:
        /home/etcd:
          partition: none
          filesystem: tmpfs
          erase_on_boot: false
          options: size=512m
      scalyr_account_key: '{{Arguments.ScalyrAccountKey}}'
    Type: Senza::TaupageAutoScalingGroup
    AutoScaling:
      Minimum: 3
      Maximum: 5
      MetricType: CPU
SenzaInfo:
  StackName: etcd-cluster
  Parameters:
  - ScalyrAccountKey:
      Description: scalyr account key
Resources:
  EtcdSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Etcd Appliance Security Group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 2379
        ToPort: 2380
        CidrIp: 0.0.0.0/0
  EtcdRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: AmazonEC2ReadOnlyAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: ec2:Describe*
            Resource: "*"
          - Effect: Allow
            Action: autoscaling:Describe*
            Resource: "*"
      - PolicyName: AmazonRoute53Access
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - route53:ListHostedZonesByName
            - route53:ChangeResourceRecordSets
            - route53:GetHostedZone
            - route53:ListResourceRecordSets
            - route53:GetChange
            Resource: [ "*" ]
