# Validation: required environment variables
%w(PACT_BROKER_DATABASE_USERNAME
   PACT_BROKER_DATABASE_PASSWORD
   PACT_BROKER_DATABASE_HOST
   PACT_BROKER_DATABASE_NAME
   APPDYNAMICS_ANALYTICS_API_ENDPOINT
   APPDYNAMICS_ACCOUNT_ID
   APPDYNAMICS_API_KEY
   EMPLOYEES_API_URL
   TOKENINFO_URL_PARAMS).each do |var|
  raise ArgumentError, "Need environment variable '#{var}'" unless ENV[var]
end
