# Validation: required environment variables
%w(PACT_BROKER_DATABASE_USERNAME
   PACT_BROKER_DATABASE_PASSWORD
   PACT_BROKER_DATABASE_HOST
   PACT_BROKER_DATABASE_NAME
   PACT_BROKER_PORT
   TOKENINFO_URL
   TOKENINFO_PARAMS
   TOKENINFO_URL_PARAMS
   OAUTH2_ACCESS_TOKEN_URL_PARAMS
   APPDYNAMICS_ANALYTICS_API_ENDPOINT
   APPDYNAMICS_ACCOUNT_ID
   APPDYNAMICS_API_KEY
   EMPLOYEES_API_URL
   SERVICES_API_URL
   BIND_TO
   SKIP_HTTPS_ENFORCER).each do |var|
  raise ArgumentError, "Need environment variable '#{var}'" unless ENV[var]
end
